"""empty message

Revision ID: af33cffd6c42
Revises: 
Create Date: 2022-08-02 17:21:08.903421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af33cffd6c42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('pokemon', sa.String(length=250), nullable=False),
    sa.Column('ability', sa.String(length=250), nullable=False),
    sa.Column('img_url', sa.String(length=250), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pokemon_id'),
    sa.UniqueConstraint('pokemon')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
